# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLQ3kBE6qSymqHXv8vJSbSmCSE-3kET8
"""



"""1)Find the minimum and maximum element in an array."""

li=[1,2,3,4,5,6,7]
print(min(li))
print(max(li))

"""2)arr[] = {1,5,3,2}
Given a random set of numbers, print them in sorted order
"""

arr={1,5,3,2}
print(sorted(arr))

"""3)write a program to reverse the array"""

a=["apple","banana","cherry"]
a.reverse()
print(a)

"""4)Find the smallest and largest element In an array"""

a=[1,3,5,7,9,12]
small=min(a)
large=max(a)
print("small",small)
print("large",large)

"""5)create three arrays and find the common element in these array"""

a=["apple","kiwi","cherry"]
b=["kiwi","orange","apple"]
c=["grape","banana","apple"]
d=(set(a).intersection(b).intersection (c))
#print(list(d))
print(d)

"""6)Find the factorial of a number using array"""

def factorial():
   n=int(input("enter a number"))
   fact=1
   for i in range(1,n+1):
      fact=fact*i
   print(fact)
factorial()

"""7)Rearrange the array in alternating positive and negative items"""

a=[1,-2,6,7,5,-8,-3]

"""# New section"""